ARG node_version

FROM node:${node_version}

WORKDIR /usr/src/app

# In case custom package from verdaccio.biyectiva.com is needed
# ARG npm_token
# RUN npm set engine-strict true
# RUN npm set registry https://verdaccio.biyectiva.com/
# RUN npm set always-auth true
# RUN npm set //verdaccio.biyectiva.com/:_authToken ${npm_token}
